backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date de publication", name: "date", widget: "datetime" }
      - { label: "Temps de lecture", name: "reading_time", widget: "string", default: "4 min" }
      - { label: "Niveau", name: "level", widget: "select", options: ["Débutant", "Intermédiaire", "Avancé"] }
      - { label: "Image miniature", name: "thumbnail", widget: "image" }
      - { label: "Résumé court", name: "description", widget: "text" }
      - { label: "Contenu de l'article", name: "body", widget: "markdown" }
